In [1]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [10]:
x = arr > 42

In [11]:
print(x)

[False False  True  True]


In [13]:
arr[x]

array([43, 44])

In [14]:
import numpy as np
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)
print(z)

[ 5  7  9 11]


In [15]:
num1 = 4
num2 = 6
x = np.lcm(num1, num2)  
print(x)

12


In [16]:
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

18


In [17]:
arr = np.arange(1, 11)

In [18]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
import pandas as pd
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}
myvar = pd.DataFrame(mydataset)
print(myvar)


    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [20]:
import pandas as pd
a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64


In [21]:
a = [1, 7, 2]
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)


x    1
y    7
z    2
dtype: int64


In [23]:
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories, index = ["day1", "day3"])
print(myvar)

day1    420
day3    390
dtype: int64


In [24]:
import pandas as pd
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}
myvar = pd.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [26]:
myvar.loc[1]

cars        Volvo
passings        7
Name: 1, dtype: object

In [ ]:
df = pd.read_csv(r"C:\Users\Ibrahim\Desktop\Load.csv")


In [29]:
print(df)

     Name   Age  Marks
0     NaN   NaN    NaN
1    John  21.0  564.0
2    Ajay  22.0  456.0
3   Nilly  21.0  654.0
4   Billy  23.0  345.0
5    Jose  22.0  456.0
6    John  21.0  564.0
7    Ajay  22.0  456.0
8   Nilly  21.0  654.0
9   Billy  23.0  345.0
10   Jose  22.0  456.0


In [37]:
df[['Age','Marks']]= df[['Age','Marks']].fillna(0).astype('i8')

In [38]:
print(df)

     Name  Age  Marks
0     NaN    0      0
1    John   21    564
2    Ajay   22    456
3   Nilly   21    654
4   Billy   23    345
5    Jose   22    456
6    John   21    564
7    Ajay   22    456
8   Nilly   21    654
9   Billy   23    345
10   Jose   22    456


In [39]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7      True
8      True
9      True
10     True
dtype: bool

In [40]:
df.drop_duplicates(inplace=True)

In [41]:
df

,Name,Age,Marks
0,NaN,0,0
1,John,21,564
2,Ajay,22,456
3,Nilly,21,654
4,Billy,23,345
5,Jose,22,456


In [42]:
print(pd.options.display.max_rows) 

60


In [43]:
pd.options.display.max_rows = 9999

In [44]:
print(pd.options.display.max_rows) 

9999


In [47]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     6 non-null      int64 
 2   Marks   6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 192.0+ bytes
None
