In [1]:
import numpy as np

In [2]:
a = np.array(42)
# b = np.array([1, 2, 3, 4, 5])
# c = np.array([[1, 2, 3], [4, 5, 6]])
# d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [3]:
print(a)

42


In [5]:
b = np.array([1,2,3,4])

In [6]:
print(b)

[1 2 3 4]


In [7]:
c = np.array([[1,2,3],[4,5,6]])

In [8]:
print(c)

[[1 2 3]
 [4 5 6]]


In [11]:
print(c.ndim)

2


In [ ]:
d = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,11,12]]])



In [18]:
print(d[1,0,2])

8


In [19]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,4])


10


In [20]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])


6


In [21]:
listnew =[1,2,3,4]

In [23]:
listnew[2
]

3

In [24]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [26]:
print(arr[1,-2])

9


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:-1])

[2 3 4 5 6]


In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


In [35]:
print(arr[1, 1:4:2])

[7 9]


In [13]:
sales = np.array([100, 120, 140, 160, 180]) 
 
print("Total Sales:", np.sum(sales)) 
print("Average Sales:", np.mean(sales)) 
print("Highest Sales:", np.max(sales))

Total Sales: 700
Average Sales: 140.0
Highest Sales: 180


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4],dtype='S')

print(arr.dtype)
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

|S1
<U6


In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)
arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int64


In [18]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [23]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
newarr = arr.reshape(2, 3, 2)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
import numpy as np

arr = np.array([1,2,3])

In [27]:
print(arr)

[1 2 3]


In [28]:
arr = np.array([[1,2,3],[4,5,6]])

In [32]:
print(arr[1,1])

5


In [37]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 2, 3], [41, 5, 6]]])
print(d[1,0,1])


2


In [38]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[2] + arr[3])


1
7


In [39]:

import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,4])
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])


10
6


In [44]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, ::-1])

Last element from 2nd dim:  [10  9  8  7  6]


In [51]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])


[7 8 9]


In [53]:
print(arr[0:2,2])

[3 8]


In [54]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [55]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [56]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [57]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [58]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [59]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [61]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print(arr)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [62]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)


[[[[[1 2 3 4]]]]]


In [63]:
print('shape of array :', arr.shape)

shape of array : (1, 1, 1, 1, 4)


In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [65]:
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
